name: Deploy Website

on:
  push:
    branches:
      - main  # change if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync files to Ubuntu server
        run: |
          rsync -avz --delete ./index.html ./styles.css deployuser@your_server_ip:/var/www/html/
